<?xml version="1.0"?>
<package format="2">

  <name>viso2_ros</name>
  <version>1.0.1</version>

  <description>This is the ROS wrapper for libviso2, library for visual odometry (see package libviso2).</description>

  <license>GPL</license>

  <url type="website">http://ros.org/wiki/viso2_ros</url>
  <url type="bugtracker">https://github.com/srv/viso2/issues</url>

  <author email="stephan.wirth@uib.es">Stephan Wirth</author>
  <maintainer email="bo-miquel.nordfeldt@uib.eu">Bo Miquel Nordfeldt-Fiol</maintainer>

  <!-- Build tool -->
  <buildtool_depend>catkin</buildtool_depend>

  <!-- System Dependencies -->
  <depend>libpcl-all-dev</depend>

  <!-- Library (Build + Exec) -->
  <depend>libviso2</depend>

  <!-- ROS Dependencies (Build + Exec) -->
  <depend>tf2</depend> 
  <depend>roscpp</depend>
  <depend>tf2_ros</depend>
  <depend>pcl_ros</depend>
  <depend>std_srvs</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend> 
  <depend>cv_bridge</depend> 
  <depend>sensor_msgs</depend>
  <depend>image_geometry</depend> 
  <depend>message_filters</depend> 
  <depend>image_transport</depend>
  <depend>tf2_geometry_msgs</depend>

  <!-- Only Build -->
  <build_depend>message_generation</build_depend>

  <!-- Only Exec -->
  <exec_depend>message_runtime</exec_depend>

</package>
